version: '3.1'

services:
    crm_api_gateway:
      image: salihcantekin/crmapigateway:latest
      ports:
        - 90:1000
      networks:
        - crmapi_network
      deploy:
        placement:
          constraints:
            - node.role == manager
        replicas: 1
        restart_policy:
          condition: on-failure
          max_attempts: 3

networks:
  crmapi_network: